// This file was auto-generated by ML.NET Model Builder. 

using System;
using System.Linq;
using Multiclass_Classification_BatchML.Model;

namespace Multiclass_Classification_BatchML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Hotel = @"Resort Hotel",
                Lead_time = 37F,
                Arrival_date_month = @"July",
                Arrival_date_week_number = 27F,
                Arrival_date_day_of_month = 1F,
                Stays_in_weekend_nights = 0F,
                Stays_in_week_nights = 4F,
                Adults = 2F,
                Children = 0F,
                Babies = 0F,
                Meal = @"BB",
                Country = @"PRT",
                Market_segment = @"Offline TA/TO",
                Distribution_channel = @"TA/TO",
                Is_repeated_guest = 0F,
                Previous_cancellations = 0F,
                Previous_bookings_not_canceled = 0F,
                Reserved_room_type = @"E",
                Assigned_room_type = @"E",
                Booking_changes = 0F,
                Days_in_waiting_list = 0F,
                Customer_type = @"Contract",
                Adr = 97.5F,
                Required_car_parking_spaces = 0F,
                Total_of_special_requests = 0F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Reservation_status with predicted Reservation_status from sample data...\n\n");
            Console.WriteLine($"Hotel: {sampleData.Hotel}");
            Console.WriteLine($"Lead_time: {sampleData.Lead_time}");
            Console.WriteLine($"Arrival_date_month: {sampleData.Arrival_date_month}");
            Console.WriteLine($"Arrival_date_week_number: {sampleData.Arrival_date_week_number}");
            Console.WriteLine($"Arrival_date_day_of_month: {sampleData.Arrival_date_day_of_month}");
            Console.WriteLine($"Stays_in_weekend_nights: {sampleData.Stays_in_weekend_nights}");
            Console.WriteLine($"Stays_in_week_nights: {sampleData.Stays_in_week_nights}");
            Console.WriteLine($"Adults: {sampleData.Adults}");
            Console.WriteLine($"Children: {sampleData.Children}");
            Console.WriteLine($"Babies: {sampleData.Babies}");
            Console.WriteLine($"Meal: {sampleData.Meal}");
            Console.WriteLine($"Country: {sampleData.Country}");
            Console.WriteLine($"Market_segment: {sampleData.Market_segment}");
            Console.WriteLine($"Distribution_channel: {sampleData.Distribution_channel}");
            Console.WriteLine($"Is_repeated_guest: {sampleData.Is_repeated_guest}");
            Console.WriteLine($"Previous_cancellations: {sampleData.Previous_cancellations}");
            Console.WriteLine($"Previous_bookings_not_canceled: {sampleData.Previous_bookings_not_canceled}");
            Console.WriteLine($"Reserved_room_type: {sampleData.Reserved_room_type}");
            Console.WriteLine($"Assigned_room_type: {sampleData.Assigned_room_type}");
            Console.WriteLine($"Booking_changes: {sampleData.Booking_changes}");
            Console.WriteLine($"Days_in_waiting_list: {sampleData.Days_in_waiting_list}");
            Console.WriteLine($"Customer_type: {sampleData.Customer_type}");
            Console.WriteLine($"Adr: {sampleData.Adr}");
            Console.WriteLine($"Required_car_parking_spaces: {sampleData.Required_car_parking_spaces}");
            Console.WriteLine($"Total_of_special_requests: {sampleData.Total_of_special_requests}");
            Console.WriteLine($"\n\nPredicted Reservation_status value {predictionResult.Prediction} \nPredicted Reservation_status scores: [{String.Join(",", predictionResult.Score)}]\n\n");

            var predictionResultBatch = ConsumeModel.PredictBatch(@"C:\repos\Multiclass_Classification_Batch\Data\Predict\hotel_bookings_batch.csv");

            Console.WriteLine("Using model to make batch prediction -- Comparing actual Reservation_status with predicted Reservation_status from sample data...\n\n");
            Console.WriteLine($"\n\nPredicted Reservation_status value {predictionResultBatch.First().Prediction} \nPredicted Reservation_status scores: [{String.Join(",", predictionResult.Score)}]\n\n");

            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
